Add additional data structures and extra submission examples
ONSdigital/ons-schema-definitions pull request #50
Opened 2020-12-01 11:08 UTC by berroar

## Context

Updates the EQ schema definitions json schema to include the latest data structures.

The following fields have been removed as they are no longer part of the submission data: `response_id`, `case_type`.

I have added the schema definition for `relationship` answer types:

```
{
   "answer_id": "relationship-answer",
    "value": [
      {
        "list_item_id": "EINoLs",
         "to_list_item_id": "TLXLDb",
         "relationship": "Husband or wife"
       }
    ]
}
```

 and `address` answer types:
```
{
  "answer_id": "address-answer",
   "value": {
       "line1": "Address Line 1",
       "town": "Town",
       "postcode": "NP10 8XG",
     },
 }
```

I have also added the `same_name_items` field to the `Lists` definition`

The `eq_submisson_example` json file has been expanded to include more answer types.

## How to test

Use the `eq_submssion_example` or generate a submission object from one of the Census schemas and validate it against the updated JSON schema using:

`pipenv run python ./schemas/json_validator.py ./schemas/eq_submission_schema.json ./examples/eq_submission_example.json`

2020-12-01 11:09 UTC, berroar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Test ONS Schema Definitions submission validator](https://trello.com/c/Wg2d4Brw/4362-test-ons-schema-definitions-submission-validator)

2020-12-02 12:12 UTC, petechd requested changes
I've just tested it and "response_id" is required but no longer part of submission json.

2020-12-02 12:23 UTC, petechd approved these changes

2020-12-02 12:23 UTC, petechd approved these changes

2020-12-04 09:12 UTC, pricem14pc requested changes
As discussed, we need to reintroduce case_type as an optional attribute.

2020-12-04 09:27 UTC, berroar commented
> As discussed, we need to reintroduce case_type as an optional attribute.

Added case type again and it is now optional.

2020-12-04 09:58 UTC, pricem14pc requested changes

2020-12-04 09:58 UTC, pricem14pc commented on schemas/eq_submission_schema.json
> +                                  "town",
Only line1 is mandatory for our current runner address answer type implementation.

2020-12-04 09:58 UTC, pricem14pc commented on schemas/eq_submission_schema.json
> +                                      "line1": "Address Line 1",
Can we also add line2 for completeness

2020-12-04 14:42 UTC, pricem14pc approved these changes
Working as expected. Caveat that the current address answer type object is currently the only object definition that this schema will support/validate. If/when other composite object answers are introduced this will need revisiting as it will expect those objects to conform to the mandatory address line1 attribute. This may just be a case of removing the required line and accept that validating composite answers is simply a business questionnaire validation concern and not the responsibility of the response payload validation.

2020-12-04 14:50 UTC, merged