Rename survey-url to schema-url
ONSdigital/ons-schema-definitions pull request #66
Opened 2022-04-20 13:06 UTC by berroar

# Context
Updated the readme as`survey_url` has been renamed to be `schema_url`

# Links

2022-04-20 13:07 UTC, berroar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Rename survey_url to schema_url (1 SP)](https://trello.com/c/hmx77oFC/5244-rename-surveyurl-to-schemaurl-1-sp)

2022-04-20 14:30 UTC, petechd approved these changes

2022-04-20 14:45 UTC, petechd requested changes
Do we want to make changes in v3 branch?

2022-04-21 09:55 UTC, berroar commented
> Do we want to make changes in v3 branch as well?

Updated the base branch now

2022-04-28 13:25 UTC, pricem14pc approved these changes

2022-04-28 14:58 UTC, merged